# Generated by Django 3.2.5 on 2021-07-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0003_site_iso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
